# Generated by Django 6.0.1 on 2026-01-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
