# Generated by Django 6.0.1 on 2026-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='uploads/product/bag1.PNG', null=True, upload_to='uploads/product/'),
        ),
    ]
