# Generated by Django 6.0.1 on 2026-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_receipt',
        ),
        migrations.AddField(
            model_name='order',
            name='fonepay_txn_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
